# Generated by Django 6.1 on 2026-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="color",
            field=models.CharField(default="", max_length=20),
        ),
    ]
