# Generated by Django 6.1 on 2026-08-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categorias", "0001_initial"),
        ("productos", "0002_producto_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos",
                to="categorias.categoria",
            ),
        ),
    ]
